#!/bin/bash
# Quick demo of the Onboarding Wizard

echo "╔════════════════════════════════════════════════════════════╗"
echo "║          SABLECORE ONBOARDING WIZARD DEMO                  ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "The wizard guides you through:"
echo "  1. 🎯 Use Case Selection (Personal, Developer, Business, etc)"
echo "  2. 📱 Platform Setup (Telegram, Discord, WhatsApp, CLI)"
echo "  3. 🎭 Personality Configuration"
echo "  4. 🛠️  Skills Installation"
echo "  5. 🔗 Integration Setup (Email, Calendar, GitHub, etc)"
echo "  6. 💾 Save Configuration"
echo ""
echo "To run the wizard:"
echo "  python main.py"
echo ""
echo "Or from the main menu:"
echo "  python main.py"
echo "  → Select option 1"
echo ""
echo "The wizard is fully interactive and saves your config to:"
echo "  config/onboarding.json"
echo ""
