"""
RBAC permission mapping for all tool schemas.
Maps schema tool name → security ActionType string.
"""

TOOL_PERMISSIONS = {
    # File / System
    "execute_command": "system_command",
    "read_file": "file_read",
    "write_file": "file_write",
    "edit_file": "file_write",
    "delete_file": "file_delete",
    "move_file": "file_write",
    "copy_file": "file_write",
    "create_directory": "file_write",
    # Browser
    "browser_search": "browser_navigate",
    "browser_scrape": "browser_navigate",
    "browser_snapshot": "browser_navigate",
    "browser_action": "browser_navigate",
    # Code execution
    "execute_code": "system_command",
    # Desktop control
    "desktop_screenshot": "system_command",
    "desktop_click": "system_command",
    "desktop_type": "system_command",
    "desktop_hotkey": "system_command",
    # Document & email
    "email_send": "email_send",
    "email_read": "email_read",
    "create_document": "file_write",
    "create_spreadsheet": "file_write",
    "create_pdf": "file_write",
    "create_presentation": "file_write",
    "open_document": "system_command",
    "write_in_writer": "system_command",
    "clipboard_copy": "system_command",
    "clipboard_paste": "system_command",
    # Trading
    "trading_portfolio": "trading_read",
    "trading_price": "trading_read",
    "trading_analyze": "trading_read",
    "trading_signals": "trading_read",
    "trading_history": "trading_read",
    "trading_risk_status": "trading_read",
    "trading_place_trade": "trading_execute",
    "trading_cancel_order": "trading_execute",
    "trading_start_scan": "trading_execute",
    "trading_stop_scan": "trading_execute",
    # Instagram
    "ig_upload_photo": "social_write",
    "ig_upload_reel": "social_write",
    "ig_upload_story": "social_write",
    "ig_search_users": "social_read",
    "ig_search_hashtags": "social_read",
    "ig_get_user_info": "social_read",
    "ig_get_timeline": "social_read",
    "ig_like_media": "social_write",
    "ig_comment": "social_write",
    "ig_follow_user": "social_write",
    "ig_send_dm": "social_write",
    "ig_get_media_comments": "social_read",
    # Facebook
    "fb_post": "social_write",
    "fb_upload_photo": "social_write",
    "fb_get_feed": "social_read",
    "fb_like_post": "social_write",
    "fb_comment": "social_write",
    "fb_get_profile": "social_read",
    "fb_search": "social_read",
    # LinkedIn
    "linkedin_get_profile": "social_read",
    "linkedin_search_people": "social_read",
    "linkedin_search_companies": "social_read",
    "linkedin_search_jobs": "social_read",
    "linkedin_post_update": "social_write",
    "linkedin_send_message": "social_write",
    "linkedin_send_connection": "social_write",
    "linkedin_get_feed": "social_read",
    # TikTok (read-only)
    "tiktok_trending": "social_read",
    "tiktok_search_videos": "social_read",
    "tiktok_search_users": "social_read",
    "tiktok_get_user_info": "social_read",
    "tiktok_get_user_videos": "social_read",
    "tiktok_get_hashtag_videos": "social_read",
    # YouTube
    "yt_search_videos": "social_read",
    "yt_search_channels": "social_read",
    "yt_get_channel": "social_read",
    "yt_get_channel_videos": "social_read",
    "yt_get_video": "social_read",
    "yt_get_comments": "social_read",
    "yt_comment": "social_write",
    "yt_get_playlist": "social_read",
    "yt_rate_video": "social_write",
    "yt_subscribe": "social_write",
    "yt_trending": "social_read",
    "yt_upload_video": "social_write",
    # Skills Marketplace
    "marketplace_search": "marketplace_read",
    "marketplace_info": "marketplace_read",
    "marketplace_install": "marketplace_install",
    "marketplace_review": "marketplace_write",
    # Mobile phone
    "phone_notify": "mobile_write",
    "phone_reminder": "mobile_write",
    "phone_geofence": "mobile_write",
    "phone_location": "mobile_read",
    "phone_device": "mobile_read",
}
